- title: DreamTime is an application for adults.
  photo: tos--adults
  content: |-
    DreamTime is an application that uses artificial intelligence to create fake-nudes from photos, if you have not reached the legal age of your country please close and uninstall this application.

- title: DreamTime is free and open-source.
  photo: tos--opensource
  content: |-
    This application is completely free and its source code is available to the public. Avoid falling for SCAMs or malware and ignore anyone who offers a premium/cracked version.

- title: Don't use DreamTime with malicious purposes.
  photo: tos--legal
  content: |-
    This application has been created exclusively for private, artistic or educational use as long as you have the permission of those involved.

    **Malicious or illegal use is totally prohibited.**

- title: Support us for more updates!
  photo: tos--love
  content: |-
    With your support we can continue to improve the application and the algorithm.
    
    Visit `www.dreamtime.tech` for more information.
