name: Build Release

on:
  push:
    tags:
      - v*
      
jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.type }})
    runs-on: ${{ matrix.os }}

    # Strategy
    # (variables for multiple platforms)
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-2019
          - ubuntu-18.04
          - macos-10.15
        type:
          - installer
          - portable

        include:
          - os: ubuntu-18.04 # Ubuntu
            platform: ubuntu
            extension: snap
          - os: windows-2019 # Windows
            platform: windows
            extension: exe
          - os: macos-10.15 # macOS
            platform: macos
            extension: dmg

    steps:
      - uses: actions/checkout@v1

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}

      - name: Install Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        working-directory: src/
        run: yarn install --network-timeout 1000000

      - name: Build Installer
        working-directory: src/
        if: matrix.type == 'installer'
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: yarn run build

      - name: Build Portable
        working-directory: src/
        if: matrix.type == 'portable'
        env:
          GITHUB_SHA: ${{ github.sha }}
          BUILD_PORTABLE: true
        run: yarn run build

      - uses: actions/upload-artifact@v2
        with:
          name: dreamtime-${{ matrix.platform }}-${{ matrix.type }}
          path: |
            dist/*.zip
            dist/*.exe
            dist/*.snap
            dist/*.dmg

      - uses: actions/upload-artifact@v2
        with:
          name: dreamtime-${{ matrix.platform }}-${{ matrix.type }}-static
          path: src/dist

      - name: Deploy to Storage
        working-directory: src/
        continue-on-error: true
        timeout-minutes: 20
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          BUILD_PLATFORM: ${{ matrix.platform }}
          BUILD_EXTENSION: ${{ matrix.extension }}
          DREAMTRACK_HOST: https://track.dreamnet.tech
          DREAMTRACK_KEY: ${{ secrets.DREAMTRACK_KEY }}
          DEPLOY_ENCRYPT_KEY: ${{ secrets.DEPLOY_ENCRYPT_KEY }}
          DEPLOY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_GITHUB_OWNER: dreamnettech
          DEPLOY_TEKNIK_TOKEN: ${{ secrets.DEPLOY_TEKNIK_TOKEN }}
          DEPLOY_TEKNIK_OWNER: dreamnet
          DEPLOY_PINATA_TOKEN: ${{ secrets.DEPLOY_PINATA_TOKEN }}
          DEPLOY_MEGA_EMAIL: ${{ secrets.DEPLOY_MEGA_EMAIL }}
          DEPLOY_MEGA_PASSWORD: ${{ secrets.DEPLOY_MEGA_PASSWORD }}
          DEPLOY_MEGA_FOLDER: /Projects/DreamTime/Releases/
          DEPLOY_MINIO_ADDRESS: /dns4/s3.dreamnet.tech/tcp/443/https
          DEPLOY_MINIO_BUCKET: dreamtime
          DEPLOY_MINIO_KEY: ${{ secrets.DEPLOY_MINIO_KEY }}
          DEPLOY_MINIO_SECRET: ${{ secrets.DEPLOY_MINIO_SECRET }}
          DEPLOY_MINIO_GATEWAY: https://s3.dreamnet.tech
          DEPLOY_DREAMLINKCLUSTER_USERNAME: dreamnet
          DEPLOY_DREAMLINKCLUSTER_PASSWORD: ${{ secrets.DEPLOY_DREAMLINKCLUSTER_PASSWORD }}
        run: yarn run deploy

      - name: Deploy to Snapcraft
        if: matrix.type == 'installer' && matrix.platform == 'ubuntu'
        working-directory: dist/
        run: snapcraft upload --release=candidate *.snap
