name: Release

on:
  workflow_dispatch:
  push:
    tags: [v*]

env:
  NODE_ENV: production 

jobs:
  # Setup
  setup:
    name: Setup
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]

    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v2

      - name: 📦 Cache node_modules
        uses: actions/cache@v2
        working-directory: src
        env:
          cache-name: dreamtime-v1-cache
        with:
          path: |
            node_modules
            !node_modules/.cache
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: 🧰 Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: 👨🏻‍💻 Install dependencies
        working-directory: src
        run: yarn install

  # Build frontend
  build-frontend:
    name: Frontend
    needs: setup
    runs-on: ubuntu-18.04

    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v2

      - name: 📦 Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: dreamtime-v1-cache
        with:
          path: |
            node_modules
            !node_modules/.cache
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: 🧰 Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: 🏗️ Build Electron
        working-directory: src
        run: yarn run build:babel

      - name: 🏗️ Build NuxtJS
        working-directory: src
        run: yarn run build:nuxt

      - name: ✨ Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dreamtime-dist
          path: |
            src/dist
            src/electron/dist
  
  # Build Electron
  build-electron:
    name: "Electron: ${{ matrix.type }} - ${{ matrix.target }} (${{ matrix.os }})"
    needs: build-frontend
    runs-on: ${{ matrix.os }}

    # Strategy
    # (variables for multiple platforms)
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
        type: [installer, portable]
        target: [default]

        include:
          - target: AppImage # Linux: AppImage
            os: ubuntu-18.04
            type: installer
          - target: rpm # Red Hat, Suse and Fedora Linux
            os: ubuntu-18.04
            type: installer

    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v2

      - name: 📦 Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: dreamtime-v1-cache
        with:
          path: |
            node_modules
            !node_modules/.cache
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: 🧰 Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      
      - uses: actions/download-artifact@v2
        with:
          name: dreamtime-dist
          path: src

      - name: 🏗️ Build ENV
        working-directory: src
        env:
          GITHUB_SHA: ${{ github.sha }}
          BUILD_PORTABLE: ${{ matrix.type == 'portable' }}
          BUILD_TARGET: ${{ matrix.target }}
        run: yarn run build:env

      - name: 🏗️ Build Electron
        working-directory: src
        run: yarn run build:electron

      - uses: actions/upload-artifact@v2
        with:
          name: dreamtime-${{ matrix.os }}-${{ matrix.type }}-${{ matrix.target }}
          path: |
            dist/*.7z
            dist/*.exe
            dist/*.snap
            dist/*.AppImage
            dist/*.rpm
            dist/*.pacman
            dist/*.dmg

      - name: 🚀 Deploy
        working-directory: src
        continue-on-error: true
        timeout-minutes: 20
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          DEPLOY_DREAMTRACK_HOST: https://track.opendreamnet.com
          DEPLOY_DREAMTRACK_KEY: ${{ secrets.DREAMTRACK_KEY }}
          DEPLOY_ENCRYPT_KEY: ${{ secrets.DEPLOY_ENCRYPT_KEY }}
          DEPLOY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_GITHUB_OWNER: dreamnettech
          DEPLOY_TEKNIK_TOKEN: ${{ secrets.DEPLOY_TEKNIK_TOKEN }}
          DEPLOY_TEKNIK_OWNER: dreamnet
          DEPLOY_PINATA_TOKEN: ${{ secrets.DEPLOY_PINATA_TOKEN }}
          DEPLOY_MEGA_EMAIL: ${{ secrets.DEPLOY_MEGA_EMAIL }}
          DEPLOY_MEGA_PASSWORD: ${{ secrets.DEPLOY_MEGA_PASSWORD }}
          DEPLOY_MEGA_FOLDER: /Projects/DreamTime/Releases/
          DEPLOY_DREAMLINKCLUSTER_USERNAME: dreamnet
          DEPLOY_DREAMLINKCLUSTER_PASSWORD: ${{ secrets.DEPLOY_DREAMLINKCLUSTER_PASSWORD }}
        run: yarn run deploy

      - name: 🐧 Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}

      - name: 🚀 Deploy to Snapcraft
        if: matrix.os == 'ubuntu-18.04' && matrix.type == 'installer' && matrix.target == 'default'
        working-directory: dist
        run: snapcraft upload *.snap
