name: Build

on:
  push:
    paths:
      - src/**
      - "!src/.vscode/**"
      - "!src/test/**"
      - "!src/.codeclimate.yml"
      - "!src/.editorconfig"
      - "!src/.gitignore"
    branches:
      - hotfix/*
      - release/*
      - canary
  workflow_dispatch:

jobs:
  build:
    name: "${{ matrix.os }}: ${{ matrix.type }} (${{ matrix.format }})"
    runs-on: ${{ matrix.os }}

    # Strategy
    # (variables for multiple platforms)
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
        type: [installer, portable]
        format: [default]

        include:
          - format: AppImage # Linux: AppImage
            os: ubuntu-18.04
            type: installer
          - format: rpm # Red Hat, Suse and Fedora Linux
            os: ubuntu-18.04
            type: installer
          - format: pacman # Arch Linux
            os: ubuntu-18.04
            type: installer

    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        working-directory: src/
        run: yarn install --network-timeout 1000000

      - name: Build Installer
        working-directory: src/
        if: matrix.type == 'installer'
        env:
          GITHUB_SHA: ${{ github.sha }}
          BUILD_FORMAT: ${{ matrix.format }}
        run: yarn run build

      - name: Build Portable
        working-directory: src/
        if: matrix.type == 'portable'
        env:
          GITHUB_SHA: ${{ github.sha }}
          BUILD_PORTABLE: true
          BUILD_FORMAT: ${{ matrix.format }}
        run: yarn run build

      - uses: actions/upload-artifact@v2
        with:
          name: dreamtime-${{ matrix.os }}-${{ matrix.type }}-${{ matrix.format }}
          path: |
            dist/*.7z
            dist/*.exe
            dist/*.snap
            dist/*.AppImage
            dist/*.rpm
            dist/*.pacman
            dist/*.dmg
