name: Build

on:
  push:
    paths:
      - src/**
      - .github/workflows/**
    branches:
      - hotfix/*
      - canary

jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.type }})
    runs-on: ${{ matrix.os }}

    # Strategy
    # (variables for multiple platforms)
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
        type:
          - installer
          - portable

        include:
          - os: ubuntu-latest # Ubuntu
            platform: ubuntu
            extension: snap
          - os: windows-latest # Windows
            platform: windows
            extension: exe
          - os: macOS-latest # macOS
            platform: macos
            extension: dmg

    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        working-directory: src/
        run: yarn install --network-timeout 1000000

      - name: Build Installer
        working-directory: src/
        if: matrix.type == 'installer'
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: yarn run build

      - name: Build Portable
        working-directory: src/
        if: matrix.type == 'portable'
        env:
          GITHUB_SHA: ${{ github.sha }}
          BUILD_PORTABLE: true
        run: yarn run build

      - uses: actions/upload-artifact@v2
        with:
          name: dreamtime-${{ matrix.platform }}-${{ matrix.type }}
          path: |
            dist/*.zip
            dist/*.exe
            dist/*.snap
            dist/*.dmg
